#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define DYNAMIC_KEYMAP_LAYER_COUNT  5
#define TRI_LAYER_LOWER_LAYER       2
#define TRI_LAYER_UPPER_LAYER       3
#define TRI_LAYER_ADJUST_LAYER      4
